### ISSUE TITLE
Adjust permission for external contributors

### ISSUE THREAD

**Issue by fdiblen** [ci-for-science/self-hosted-runners#12] opened 2020-06-10 13:56 UTC
As running the workflow on a custom server can be very expensive, we want to limit this to external contributors.

One option is to run CI for only a protected branch.
See 
https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions
https://help.github.com/en/github/administering-a-repository/configuring-protected-branches

**Comment by HannoSpreeuw** [comment] 2020-06-12 09:17
I need access to settings to enforce those permissions, which I don't currently have.
So the settings tab is missing - for me - from the main page of the repo.

**Comment by felipeZ** [comment] 2020-06-12 12:27
@HannoSpreeuw  I have granted you admin access :)

**Comment by HannoSpreeuw** [comment] 2020-06-12 15:31
Since CI is performed before every merge of a pull request, I guess we have to **configure the CI workflow such that it is limited to certain users or with other restrictions**. But I don't know if that's possible.

I don't see how you can configure protected branches or enable branch restrictions such that CI is only performed with certain conditions. CI does not seem to be controlled at the level of the branches.
So I don't think CI configuration is covered by the two links above (from the OP).

**Comment by felipeZ** [comment] 2020-06-15 07:10
@HannoSpreeuw  You can always tell GitHub to use only certain branches  by adding to the yaml file something like:
```yaml
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
```
You  can also use and [if statement]( https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif) to run a job if a condition is met.

**Comment by HannoSpreeuw** [comment] 2020-06-15 08:56
Thanks. But which yaml file are you referring to?

**Comment by felipeZ** [comment] 2020-06-15 09:00
Github actions uses a yaml file to configure the CI, see for instance the [yaml file for the CI for science repo](https://github.com/NLESC-JCER/ci_for_science/tree/master/.github/workflows). This yaml file must be in the repo root folder in the path: ``./github/workflows/some_name.yml``

After a push GitHub will try to read a YAML file from that path and perform the actions described there.

**Comment by HannoSpreeuw** [comment] 2020-06-15 09:17
Thanks again. So I guess you are saying that the solutuon to this issue is not found through those two links.
> 
> One option is to run CI for only a protected branch.
> See
> https://help.github.com/en/github/administering-a-repository/enabling-branch-restrictions
> https://help.github.com/en/github/administering-a-repository/configuring-protected-branches

but rather though the CI workflow configuration.

**Comment by felipeZ** [comment] 2020-06-15 09:22
You can configure by enable some branching restrictions but also you can also configure the CI workflow directly, I found the last option more maintainable and easy to explain.

**Comment by HannoSpreeuw** [comment] 2020-06-15 10:21
Perhaps you can help me tackle this issue, because I don't know how to proceed.

**Comment by sverhoeven** [comment] 2020-06-15 10:47
I think we want to configure the runner to only execute repos and workflows which the runner whitelists. The whitelist should only be configurable by the runner administrator. See https://github.com/actions/runner/issues/494

**Comment by felipeZ** [comment] 2020-06-15 11:51
Now I understand ;)

**Comment by HannoSpreeuw** [comment] 2020-06-15 14:10
After talking to @felipeZ we decided to leave the problem pending until we are able to get in touch with @sverhoeven to shed some light on this.

**Comment by sverhoeven** [comment] 2020-06-16 15:54
My comment was an attempt to mitigate some of the risks described in https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories

**Comment by HannoSpreeuw** [comment] 2020-06-17 08:46
> @HannoSpreeuw You can always tell GitHub to use only certain branches by adding to the yaml file something like:
> 
> ```yaml
> on:
>   # Trigger the workflow on push or pull request,
>   # but only for the master branch
>   push:
>     branches:
>       - master
>   pull_request:
>     branches:
>       - master
> ```
> 
> You can also use and [if statement](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif) to run a job if a condition is met.

@felipeZ I understand this, but anyone can create a branch and add a GH workflow yaml file with completely different settings. So adding this workflow yml file to the master branch does not seem to prevent other, possibly malicious, workflows to run as well.

This is just my understanding, so please correct me if I am wrong.

**Comment by HannoSpreeuw** [comment] 2020-06-17 09:07
> I think we want to configure the runner to only execute repos and workflows which the runner whitelists. The whitelist should only be configurable by the runner administrator. See [actions/runner#494](https://github.com/actions/runner/issues/494)

@sverhoeven That issue has a [comment](https://github.com/actions/runner/issues/494#issuecomment-642868826):
```
That feature would be extremely valuable to our team. 
```
which implies that the feature we need is not available yet.

**Comment by HannoSpreeuw** [comment] 2020-06-17 09:23
> My comment was an attempt to mitigate some of the risks described in https://help.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories

@sverhoeven Thanks. But the bottom line is that self hosted runners should not be deployed from a public repository. At least that is what GH advises. So we should make our repo private.
Or do you see another way to lower the risks to an acceptable level? Some kind of firewall on our machines?

**Comment by felipeZ** [comment] 2020-06-17 09:25
> > @HannoSpreeuw You can always tell GitHub to use only certain branches by adding to the yaml file something like:
> > ```yaml
> > on:
> >   # Trigger the workflow on push or pull request,
> >   # but only for the master branch
> >   push:
> >     branches:
> >       - master
> >   pull_request:
> >     branches:
> >       - master
> > ```
> > 
> > 
> > You can also use and [if statement](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif) to run a job if a condition is met.
> 
> @felipeZ I understand this, but anyone can create a branch and add a GH workflow yaml file with completely different settings. So adding this workflow yml file to the master branch does not seem to prevent other, possibly malicious, workflows to run as well.
> 
> This is just my understanding, so please correct me if I am wrong.

@HannoSpreeuw you are right and it goes along what @sverhoeven  has posted above about securing the runner.

**Comment by cwmeijer** [comment] 2020-06-17 11:34
See #50

**Comment by HannoSpreeuw** [comment] 2020-06-17 14:28
Only local actions allowed from now on, following the suggestion by @jspaaks 

![image](https://user-images.githubusercontent.com/11661087/84910728-867c0580-b0b7-11ea-9d1f-2f12e6e1d39c.png)

Let's see if that fixes this issue.

**Comment by HannoSpreeuw** [comment] 2020-06-18 10:53
![image](https://user-images.githubusercontent.com/11661087/85011296-9bad6e80-b161-11ea-8d4a-e1c7e9431edb.png)

@jspaaks and me performed a test.
First I forked our linux_actions_runner repo through a second GH account that I own, obviously not a team member of linux_actions_runner.
Next, we modified the README.md - by just adding some spaces - and submitted a PR to upstream. We were able to change the status of packer-Ubuntu-18 (see screenshot) from Idle to Active.
This means that "Enabling local Actions only for this repository" alone does not fix this issue.
We need something more.

**Comment by HannoSpreeuw** [comment] 2020-06-18 13:34
Some extra comments, for reproducibility.

To turn the status of the self-hosted runner from "Offline" to "Idle" we run some commands similar to the ones posted [here](https://github.com/NLESC-JCER/linux_actions_runner/blob/ansible/ansible.md).
Ths is from the master branch. With the ssh key in the root directory. 
We modified the files `ubuntu-virtualbox/inventory` and `ubuntu-virtualbox/playbook-set-up-runner.yml`. The former is just contains `nlesc-ci.demo-nlesc.surf-hosted.nl` and the latter has `remote_user ubuntu`.

Next, run
`docker run --rm -ti -v ${PWD}:/gt ansible/ansible-runner /bin/bash`
in the docker shell, run 
`cd /gt`
and 
`ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook --private-key=id_rsa_ci_sprint -i ubuntu-virtualbox/inventory ubuntu-virtualbox/playbook-set-up-runner.yml -vvv`
after which you have to fill out the GH organization (NLESC-JCER),  the repo (linux_actions_runner) and the token from [here](https://github.com/nlesc-jcer/linux_actions_runner/settings/actions/add-new-runner).

If you get the message that the runner is already configured, ssh to the vm through
`ssh -i id_rsa_ci_sprint ubuntu@nlesc-ci.demo-nlesc.surf-hosted.nl`,
 `cd tmp` and `rm -rf actions-runner/`

**Comment by HannoSpreeuw** [comment] 2020-06-19 11:55
![afbeelding](https://user-images.githubusercontent.com/11661087/85128400-77b95e00-b231-11ea-93d1-9c98111feaa5.png)

I can also trigger this from my forked repo through a different GH identity (hspreeuw, no team member) after the transition to the new organisation (ci-for-science). No surprise.

But still I think this is not a safety hazard, although you could potentially generate a lot of traffic on your hardware, by generating a lot of pull requests.

I mean, I don't see how an outsider could commit malicious code or workflows to our repo unless a team member approves those PRs.

![afbeelding](https://user-images.githubusercontent.com/11661087/85129074-cc110d80-b232-11ea-968a-2cfbf69a660a.png)

If we set up branches such that outsiders can submit PRs only for certain branches and we have CI only running for other branches, we should be safe.

**Comment by sverhoeven** [comment] 2020-06-19 12:19
The [Branch protection](https://help.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests) only works on branches in your own repo, you . A PR coming from someone else containing a workflow will still be run on the self-hosted runner.

**Comment by HannoSpreeuw** [comment] 2020-06-19 12:57
Thanks. No easy way out here.
After discussion at our stand-up we found out that we cannot fix this without adding a lot of complexity and/or spend a lot more hours. 
We decided to close this issue after I have added warnings at the appropriate places.

**Closed** 2020-06-22 17:11 UTC
